title = "RpCore Stage"

[owner]
name = "Kimkic"
dob = 2018-10-23T10:42:47+02:00

[repo]
username = "kimlic"
password = "LU6dME4NzQ"
hostname = "stage-postgresql-rp2.eastus.cloudapp.azure.com"
pool_size = 10

[rp_core]
azure_container = "rp-blob"
azure_cdn_url = "https://stagerp2blob.blob.core.windows.net"

[ex_azure]
account = "stagerp2blob"
access_key ="vVxIFU45rfYw3Z5uGP0IxLaEHgENxG0JurOZYrEprDH9T4SC2atbGZfrc11CM9LIh0dSRYHOpb1wF+ZmaWrCiQ=="